version: '2'
services: 
  ${mongodb.hostname}:
    image: andrena/testing-tools-mongodb
    ports:
     - "27017:27017"
  ${imageservice.hostname}:
    image: andrena/testing-tools-image-service
    ports:
     - "8282:8282"
    links:
     - ${mongodb.hostname}
  ${weatherservice.hostname}:
    image: andrena/testing-tools-weather-service
    ports:
     - "8181:8181"
  ${clothingfrontend.hostname}:
    image: andrena/testing-tools-clothing-frontend
    ports:
     - "8843:8843"
    links:
     - ${weatherservice.hostname}
     - ${imageservice.hostname}